#+TITLE: Paperspan2Instaper
#+AUTHOR: Mari Donkers
#+STARTUP: indent
#+OPTIONS: toc:3

* Introduction

Paperspan HTML export to Instapaper CSV import with automatic designation to folders.

Usage: see the [[https://github.com/maridonkers/paperspan2instapaper/blob/master/Makefile][Makefile]].

Use a =make shell= before trying a =make build =. A =make ls= lists
the location of the executable, which you can copy and paste to run
it.

* Paperspan format
#+BEGIN_SRC html
  <!DOCTYPE html>
  <html>
   <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>PaperSpan Export</title>
   </head>
   <body>
    <h1>Unread</h1>
    <ul>
     <h2>Read Later</h2>
     <ul>
       <li><a href="https://thisisalink" time_added="1630506259000">This is a <i>description</i>.</a></li>
       ...
     </ul>
    </ul>
  ...
    <h1>Read</h1>
   <ul>
    <h2>Read Later</h2>
    <ul>
      <li> ...</li>
      ...
    </ul>
   </ul>
  </body>
#+END_SRC


* Paperspan folders
  Existing Paperspan folders are reused by the conversion program. If the =Read Later= folder is encountered then an automatic designation to folders (via regular expression rules, which are provided in a configuration file) is done. See the next section for details on this.

* Automatic designation to folders
  
Paperspan HTML export to Instapaper CSV import. With [[https://github.com/maridonkers/paperspan2instapaper/blob/master/folders-example.yaml][folders.yaml]]
configuration file, which contains Instapaper target folder names (for
output file) and [[https://github.com/niklongstone/regular-expression-cheat-sheet][regular expressions]] for =URL= or =text= in Paperspan
export (which is input). Each of the selectors in the configuration file (I have hundreds) is matched against the URL or text of the Paperspan link being umported, until a match is found and an associated folder can be designated to it. This is very useful when you have a lot of undesignated links in your Paperspan (which you did not yet move to a folder).

e.g. the Paperspan link

#+BEGIN_SRC html
      <a href="https://news360.com/article/563394549"
         time_added="1630495255000">
        Stop prescribing hydroxychloroquine for Covid-19, warn researchers | Stop News – India TV
      </a>
#+END_SRC

is matched with the following selector from [[https://github.com/maridonkers/paperspan2instapaper/blob/master/folders-example.yaml][folders.yaml]]:

#+BEGIN_SRC yaml
  - "conditionRegExp": "\\bcovid-19\\b"
    "conditionSource": "text"
    "conditionFolderName": "biologyHealth"
#+END_SRC

which results in designation to the =Biology Health= folder via its folderName (also in [[https://github.com/maridonkers/paperspan2instapaper/blob/master/folders-example.yaml][folders.yaml]]).

#+BEGIN_SRC yaml
  - "folderName": "biologyHealth"
    "folderPath": "Biology Health"
#+END_SRC

and the following CSV line is the result:

#+BEGIN_SRC csv
  https://news360.com/article/563394549,
  "Stop prescribing hydroxychloroquine for Covid-19, warn researchers | Stop News – India TV",
  https://news360.com/article/563394549,
  "Biology Health",
  1630495255000
#+END_SRC

* Blog article

  Is here: [[https://photonsphere.org/posts/2021-10-06-paperspan2instapaper.html][2021-10-06-paperspan2instapaper]].
  
* Disclaimer
This is a 'one shot' program (excuse my Haskell) that I've
used only once to import an export of my /27,689/ Paperspan article
links into Instapaper. Update: still /2,140/ undesignated links left; further refining program; adding more selector rules.
